import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({ baseDirectory: __dirname });

const eslintConfig = [
  {
    // Leading **/ so build output is ignored wherever it lives — .claude/worktrees/*
    // holds scratch checkouts with their own .next/ directories.
    ignores: [
      '**/.next/**',
      '**/.open-next/**',
      '**/.wrangler/**',
      '**/node_modules/**',
      '.claude/**',
      'public/**',
      'stripe',
      // Regenerated by `next build`; its triple-slash reference is not ours to fix.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Raw apostrophes/quotes in JSX text render correctly in React. Enforcing
      // &apos;/&quot; would mean rewriting live customer-facing email copy for
      // no rendering benefit, so this stays off deliberately.
      'react/no-unescaped-entities': 'off',
      // A leading _ marks a parameter that must exist to satisfy a signature
      // (route handlers, third-party callbacks) but is deliberately unused.
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
];

export default eslintConfig;
